// Admin actions
export const CREATE_JOB_REQUEST = "CREATE_JOB_REQUEST";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_FAILURE = "CREATE_JOB_FAILURE";

export const UPDATE_JOB_REQUEST = "UPDATE_JOB_REQUEST";
export const UPDATE_JOB_SUCCESS = "UPDATE_JOB_SUCCESS";
export const UPDATE_JOB_FAILURE = "UPDATE_JOB_FAILURE";

export const DELETE_JOB_REQUEST = "DELETE_JOB_REQUEST";
export const DELETE_JOB_SUCCESS = "DELETE_JOB_SUCCESS";
export const DELETE_JOB_FAILURE = "DELETE_JOB_FAILURE";

export const FETCH_JOB_APPLICATIONS_REQUEST = "FETCH_JOB_APPLICATIONS_REQUEST";
export const FETCH_JOB_APPLICATIONS_SUCCESS = "FETCH_JOB_APPLICATIONS_SUCCESS";
export const FETCH_JOB_APPLICATIONS_FAILURE = "FETCH_JOB_APPLICATIONS_FAILURE";
