// Job actions
export const FETCH_JOBS_REQUEST = "FETCH_JOBS_REQUEST";
export const FETCH_JOBS_SUCCESS = "FETCH_JOBS_SUCCESS";
export const FETCH_JOBS_FAILURE = "FETCH_JOBS_FAILURE";

export const APPLY_FOR_JOB_REQUEST = "APPLY_FOR_JOB_REQUEST";
export const APPLY_FOR_JOB_SUCCESS = "APPLY_FOR_JOB_SUCCESS";
export const APPLY_FOR_JOB_FAILURE = "APPLY_FOR_JOB_FAILURE";

export const FETCH_APPLIED_JOBS_REQUEST = "FETCH_APPLIED_JOBS_REQUEST";
export const FETCH_APPLIED_JOBS_SUCCESS = "FETCH_APPLIED_JOBS_SUCCESS";
export const FETCH_APPLIED_JOBS_FAILURE = "FETCH_APPLIED_JOBS_FAILURE";

export const FETCH_JOB_DETAILS_REQUEST = "FETCH_JOB_DETAILS_REQUEST";
export const FETCH_JOB_DETAILS_SUCCESS = "FETCH_JOB_DETAILS_SUCCESS";
export const FETCH_JOB_DETAILS_FAILURE = "FETCH_JOB_DETAILS_FAILURE";

